# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright (c) 2026 Ainekko, Co.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#define IREGSIZE 8
#define FREGSIZE   32
#define SAVE_IREG(nr) sd x##nr, (nr*IREGSIZE)(sp)
#define SAVE_FREG(nr)   fsq2 f##nr, (32*IREGSIZE)+(nr*FREGSIZE)(sp)
#define RESTORE_IREG(nr) ld x##nr, (nr*IREGSIZE)(sp)
#define RESTORE_FREG(nr)   flq2 f##nr, (32*IREGSIZE)+(nr*FREGSIZE)(sp)

//#define USE_FREGS
.global test_mtrap_vector
    .align 12
test_mtrap_vector:
   // make copy of registers
    addi sp, sp, -(32*IREGSIZE+32*FREGSIZE)

    SAVE_IREG(1)
    SAVE_IREG(2)
    SAVE_IREG(3)
    SAVE_IREG(4)
    SAVE_IREG(5)
    SAVE_IREG(6)
    SAVE_IREG(7)
    SAVE_IREG(8)
    SAVE_IREG(9)
    SAVE_IREG(10)
    SAVE_IREG(11)
    SAVE_IREG(12)
    SAVE_IREG(13)
    SAVE_IREG(14)
    SAVE_IREG(15)
    SAVE_IREG(16)
    SAVE_IREG(17)
    SAVE_IREG(18)
    SAVE_IREG(19)
    SAVE_IREG(20)
    SAVE_IREG(21)
    SAVE_IREG(22)
    SAVE_IREG(23)
    SAVE_IREG(24)
    SAVE_IREG(25)
    SAVE_IREG(26)
    SAVE_IREG(27)
    SAVE_IREG(28)
    SAVE_IREG(29)
    SAVE_IREG(30)
    SAVE_IREG(31)

#ifdef USE_FREGS
    SAVE_FREG(0)
    SAVE_FREG(1)
    SAVE_FREG(2)
    SAVE_FREG(3)
    SAVE_FREG(4)
    SAVE_FREG(5)
    SAVE_FREG(6)
    SAVE_FREG(7)
    SAVE_FREG(8)
    SAVE_FREG(9)
    SAVE_FREG(10)
    SAVE_FREG(11)
    SAVE_FREG(12)
    SAVE_FREG(13)
    SAVE_FREG(14)
    SAVE_FREG(15)
    SAVE_FREG(16)
    SAVE_FREG(17)
    SAVE_FREG(18)
    SAVE_FREG(19)
    SAVE_FREG(20)
    SAVE_FREG(21)
    SAVE_FREG(22)
    SAVE_FREG(23)
    SAVE_FREG(24)
    SAVE_FREG(25)
    SAVE_FREG(26)
    SAVE_FREG(27)
    SAVE_FREG(28)
    SAVE_FREG(29)
    SAVE_FREG(30)
    SAVE_FREG(31)
#endif
    // set params ( mcause, mpec, pointer to registers)
    csrr a0, mcause
    csrr a1, mepc
    csrr a2, mtval
    csrr a3, mhartid
    jal test_mtrap_handler

    // return value is next PC
    csrw mepc, a0

    // restore registers returned by the trap handler
    RESTORE_IREG(1)
    RESTORE_IREG(2)
    RESTORE_IREG(3)
    RESTORE_IREG(4)
    RESTORE_IREG(5)
    RESTORE_IREG(6)
    RESTORE_IREG(7)
    RESTORE_IREG(8)
    RESTORE_IREG(9)
    RESTORE_IREG(10)
    RESTORE_IREG(11)
    RESTORE_IREG(12)
    RESTORE_IREG(13)
    RESTORE_IREG(14)
    RESTORE_IREG(15)
    RESTORE_IREG(16)
    RESTORE_IREG(17)
    RESTORE_IREG(18)
    RESTORE_IREG(19)
    RESTORE_IREG(20)
    RESTORE_IREG(21)
    RESTORE_IREG(22)
    RESTORE_IREG(23)
    RESTORE_IREG(24)
    RESTORE_IREG(25)
    RESTORE_IREG(26)
    RESTORE_IREG(27)
    RESTORE_IREG(28)
    RESTORE_IREG(29)
    RESTORE_IREG(30)
    RESTORE_IREG(31)
#ifdef USE_FREGS
    RESTORE_FREG(0)
    RESTORE_FREG(1)
    RESTORE_FREG(2)
    RESTORE_FREG(3)
    RESTORE_FREG(4)
    RESTORE_FREG(5)
    RESTORE_FREG(6)
    RESTORE_FREG(7)
    RESTORE_FREG(8)
    RESTORE_FREG(9)
    RESTORE_FREG(10)
    RESTORE_FREG(11)
    RESTORE_FREG(12)
    RESTORE_FREG(13)
    RESTORE_FREG(14)
    RESTORE_FREG(15)
    RESTORE_FREG(16)
    RESTORE_FREG(17)
    RESTORE_FREG(18)
    RESTORE_FREG(19)
    RESTORE_FREG(20)
    RESTORE_FREG(21)
    RESTORE_FREG(22)
    RESTORE_FREG(23)
    RESTORE_FREG(24)
    RESTORE_FREG(25)
    RESTORE_FREG(26)
    RESTORE_FREG(27)
    RESTORE_FREG(28)
    RESTORE_FREG(29)
    RESTORE_FREG(30)
    RESTORE_FREG(31)
#endif

    addi sp, sp, (32*IREGSIZE+32*FREGSIZE)

    // and return
    mret
